//
// Created by tnwei on 1/19/2022.
//

#ifndef ELK_CLIENT_INCLUDE_ELK_ELASTICSEARCH_MODELS_INDEX_INDEX_ACTIONS_H_
#define ELK_CLIENT_INCLUDE_ELK_ELASTICSEARCH_MODELS_INDEX_INDEX_ACTIONS_H_

#include "magic_enum.hpp"

namespace elk {

enum class IndexAction {
  INDEX_ACTION = 0,
  CREATE_ACTION = 1,
  DELETE_ACTION = 2,
  UPDATE_ACTION = 3
};

}
#endif //ELK_CLIENT_INCLUDE_ELK_ELASTICSEARCH_MODELS_INDEX_INDEX_ACTIONS_H_
